---

- project:
    name: appc-deployment
    project-name: 'appc-deployment'
    jobs:
      - gerrit-maven-clm:
      - '{project-name}-{stream}-verify-java'
      - '{project-name}-{stream}-merge-java'
      - '{project-name}-{stream}-release-version-java-daily'
      - '{project-name}-{stream}-docker-java-daily':
          mvn-params: '-Dmaven.test.skip=true'
      - '{project-name}-{stream}-docker-version-java-daily':
          mvn-params: '-Dmaven.test.skip=true'
      - '{project-name}-docker-image-blessing'

    project: 'appc/deployment'
    stream:
      - 'master':
          branch: 'master'
      - 'beijing':
          branch: 'beijing'
    mvn-settings: 'appc-deployment-settings'
    files: '**'
    archive-artifacts: ''
    docker-pom: 'pom.xml'
    mvn-profile: docker
    build-node: ubuntu1604-builder-4c-4g
