---

- project:
    name: appc-deployment
    project-name: 'appc-deployment'
    jobs:
      - '{project-name}-{stream}-verify-java'
      - '{project-name}-{stream}-merge-java'
      - gerrit-maven-stage:
          sign-artifacts: true
          build-node: centos7-docker-8c-8g
          maven-versions-plugin: true
      - '{project-name}-{stream}-release-version-java-daily'
      - '{project-name}-docker-image-blessing'

    project: 'appc/deployment'
    stream:
      - 'master':
          branch: 'master'
    mvn-settings: 'appc-deployment-settings'
    files: '**'
    archive-artifacts: ''
    docker-pom: 'pom.xml'
    mvn-profile: docker
    build-node: ubuntu1604-builder-4c-4g

#- project:
#    name: appc-deployment-arm64
#    project-name: 'appc-deployment-arm64'
#    jobs:
#      - '{project-name}-docker-image-blessing'
#
#    project: 'appc/deployment'
#    stream:
#      - 'master':
#          branch: 'master'
#    mvn-settings: 'appc-deployment-settings'
#    files: '**'
#    archive-artifacts: ''
#    docker-pom: 'pom.xml'
#    mvn-profile: docker
#    build-node: ubuntu1604-docker-arm64-4c-2g
#
- project:
    name: appc-deployment-docker
    project-name: 'appc-deployment'
    jobs:
      - 'docker-java-daily':
          mvn-params: '-Dmaven.test.skip=true'
      - 'docker-version-java-daily':
          mvn-params: '-Dmaven.test.skip=true'
    project: 'appc/deployment'
    stream:
      - 'master':
          branch: 'master'
    mvn-settings: 'appc-deployment-settings'
    files: '**'
    archive-artifacts: ''
    docker-pom: 'pom.xml'
    mvn-profile: docker
    build-node: ubuntu1604-docker-8c-8g

#- project:
#    name: appc-deployment-arm64-docker
#    project-name: 'appc-deployment-arm64'
#    jobs:
#      - 'docker-java-daily':
#          mvn-params: '-Dmaven.test.skip=true'
#      - 'docker-version-java-daily':
#          mvn-params: '-Dmaven.test.skip=true'
#    project: 'appc/deployment'
#    stream:
#      - 'master':
#          branch: 'master'
#    mvn-settings: 'appc-deployment-settings'
#    files: '**'
#    archive-artifacts: ''
#    docker-pom: 'pom.xml'
#    mvn-profile: docker
#    build-node: ubuntu1604-docker-arm64-4c-2g

- project:
    name: appc-deployment-info
    project-name: appc-deployment
    jobs:
      - gerrit-info-yaml-verify
    project: appc/deployment
    branch: master
