---

- project:
    name: appc-deployment
    project-name: 'appc-deployment'
    jobs:
      - gerrit-maven-clm:
          java-version: ''
      - '{project-name}-{stream}-verify-java'
      - '{project-name}-{stream}-merge-java'
      - '{project-name}-{stream}-release-version-java-daily-no-sonar'
      - '{project-name}-{stream}-docker-java-daily'
      - '{project-name}-{stream}-docker-version-java-daily'
      - '{project-name}-docker-image-blessing'

    project: 'appc/deployment'
    stream:
      - 'master':
          branch: 'master'
      - 'amsterdam':
          branch: 'amsterdam'
    mvn-settings: 'appc-deployment-settings'
    files: '**'
    archive-artifacts: ''
    docker-pom: 'pom.xml'
    mvn-profile: docker
    build-node: ubuntu1604-basebuild-4c-4g
- project:
    name: appc-deployment-sonar
    jobs:
      - gerrit-maven-sonar
    build-node: ubuntu1604-basebuild-4c-4g
    java-version: ''
    project: 'appc/deployment'
    project-name: 'appc-deployment'
    branch: 'master'
    mvn-settings: 'appc-deployment-settings'
    mvn-goals: 'clean install'
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'
