---

- project:
    name: appc-deployment
    project-name: 'appc-deployment'
    jobs:
      - gerrit-maven-clm:
      - '{project-name}-{stream}-verify-java'
      - '{project-name}-{stream}-merge-java'
      - '{project-name}-{stream}-release-version-java-daily'
      - '{project-name}-{stream}-verify-docker':
          build-node: ubuntu1604-docker-8c-8g
      - '{project-name}-{stream}-merge-docker':
          build-node: ubuntu1604-docker-8c-8g
      - '{project-name}-{stream}-release-version-docker-daily-no-sonar':
          build-node: ubuntu1604-docker-8c-8g

    project: 'appc/deployment'
    stream:
      - 'master':
          branch: 'master'
    mvn-settings: 'appc-deployment-settings'
    files: '**'
    archive-artifacts: ''
    docker-pom: 'pom.xml'
    docker_build_args: '-f docker-files/Dockerfile'
    docker_name: docker-appc-deployment
    mvn-profile: docker
    build-node: ubuntu1604-builder-4c-4g
