---
- project:
    name: aai-aai-config
    project-name: 'aai-aai-config'
    jobs:
      - gerrit-maven-clm
    project: 'aai/aai-config'
    stream:
      - 'master':
          branch: 'master'
    mvn-settings: 'aai-aai-config-settings'
    files: '**'
    archive-artifacts: ''
    build-node: ubuntu1604-builder-4c-4g
