---
- project:
    name: pnfusecases-config-over-netconf-csit
    jobs:
      - '{project-name}-{stream}-verify-csit-{functionality}'
      - '{project-name}-{stream}-csit-{functionality}'
    project-name: 'pnfusecases'
    stream:
      - 'master':
          branch: 'master'
    functionality:
      - 'config-over-netconf':
          trigger_jobs:
            - '{project-name}-{stream}-docker-java-shell-daily'
    robot-options: ''
