---
- project:
    name: multicloud-k8s-kud-deployment
    project: 'multicloud/k8s'
    build-node: ubuntu1604-builder-4c-4g
    kud_build_script: !include-raw-escape: kud-deployment.sh

    stream:
      - 'master':
          branch: 'master'

    jobs:
      - '{name}-{stream}-verification':
          script: '{kud_build_script}'
