---
- project:
    name: dcaegen2-platform-deployment-handler
    project-name: 'dcaegen2-platform-deployment-handler'
    jobs:
      - '{project-name}-{stream}-verify-java'
      - '{project-name}-{stream}-merge-java'
      - '{project-name}-{stream}-release-version-java-daily'

    project: 'dcaegen2/platform/deployment-handler'
    stream:
      - 'master':
          branch: 'master'
      - 'amsterdam':
          branch: 'amsterdam'
    mvn-settings: 'dcaegen2-platform-deployment-handler-settings'
    # due to a strange macro / variable translation problem this needs
    # to be passed as a string block to properly get the properties
    # correctly defined in the job
    maven-deploy-properties: |
      deployAtEnd=true
    files: '**'
    archive-artifacts: ''
    build-node: 'ubuntu1604-docker-8c-8g'
- project:
    name: dcaegen2-platform-deployment-handler-sonar
    jobs:
      - gerrit-maven-sonar
    build-node: ubuntu1604-basebuild-4c-4g
    java-version: ''
    project: 'dcaegen2/platform/deployment-handler'
    project-name: 'dcaegen2-platform-deployment-handler'
    branch: 'master'
    mvn-settings: 'dcaegen2-platform-deployment-handler-settings'
    mvn-goals: 'clean install'
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'